version: '3.3'
services:
  fly-db:
    image: postgres:12.1
    volumes:
      - ./init-db/fly/schema.sql:/docker-entrypoint-initdb.d/1-schema.sql
      - ./init-db/fly/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - 5436:5432
